#!/bin/bash

set -e

if [ -f /usr/share/midolman/midolman-env.sh ]; then
    . /usr/share/midolman/midolman-env.sh
else
    echo "midolman-env.sh is not found"
    exit 1
fi

if [ ! -d /sys/module/openvswitch ] && [ ! -d /sys/module/openvswitch_mod ] ; then
    echo "Loading openvswitch kernel module"
    modprobe openvswitch_mod 2>/dev/null || modprobe openvswitch
fi
test -d $MIDO_LOG_DIR || mkdir -p $MIDO_LOG_DIR
if [ ! -d $QUAGGA_DIR ] ; then
    mkdir -p -m 755 $QUAGGA_DIR
    chown quagga:quagga $QUAGGA_DIR
fi

cleanup_bgp_space() {
    prefix=$1
    ns="${prefix}_ns"
    br="${prefix}_br"
    echo "cleaning up br: $br"
    brctl delif $br "${prefix}_vty"
    ip link set $br down
    brctl delbr $br

    echo "cleaning up ns: $ns"
    ip netns exec $ns ip link delete "${prefix}_m"
    ip netns exec $ns ip link delete "${prefix}_vtym"
    ip netns delete $ns
}

cleanup_bgps() {
    ps aux | grep -- '--socket /var/run/quagga/zserv' | grep -v grep | \
    while read i ; do
        pid=`echo $i | awk '{print $2}'`
        kill -9 $pid
    done

    for i in `ip netns list | grep ^mbgp` ; do
        prefix=`echo $i | sed -e 's/_ns//'`
        cleanup_bgp_space $prefix
    done
}

cleanup_bgps
